---
name: "Java CI with Maven"
"on":
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
    - "062-monitoring"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Set up JDK 11"
      uses: "actions/setup-java@v2"
      with:
        java-version: "11"
        distribution: "adopt"
    - name: "Build with Maven"
      run: "mvn compile"
    - name: "Run tests"
      run: "mvn test"
    - name: "Lint"
      run: "mvn spotless:check"
